---
title: "Chmouel's blog"
baseURL: "https://blog.chmouel.com/"
theme: "PaperMod"
languageCode: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
rssLimit: 20
ignoreLogs: ["warning-goldmark-raw-html"]
minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 10
  path: "page"

params:
  author: "Chmouel Boudjnah"
  env: production
  defaultTheme: auto
  # disableThemeToggle: true
  # ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowToc: true
  disableSpecial1stPost: true
  # label:
  #   icon: logo/chmouel.png
  #   iconHeight: 40
  assets:
    disableFingerprinting: true

  editPost:
    URL: "https://github.com/chmouel/blog/tree/main/content"
    Text: "Edit"
    appendFilePath: true

markup:
  highlight:
    style: dracula
    lineNumbersInTable: false
    tabWidth: 2
    guessSyntax: true

menus:
  main:
    - name: "camera"
      url: "https://photos.chmouel.com"
      pre: Photos
    - name: "GitHub"
      url: "https://github.com/chmouel/"
    - name: "Mastodon"
      url: "https://fosstodon.org/@chmouel"
    - name: "Twitter"
      url: "https://twitter.com/chmouel"
    - name: "Strava"
      url: "https://app.strava.com/athletes/126695"
    - name: "redhat"
      url: "https://redhat.com"
      pre: Red Hat
privacy:
  youtube:
    privacyEnhanced: true
