---
title: "Chmouel's blog"
baseURL: "https://blog.chmouel.com/"
theme: "PaperMod"
locale: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
rssLimit: 20
ignoreLogs: ["warning-goldmark-raw-html"]
minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

pagination:
  pagerSize: 10
  path: "page"

params:
  author: "Chmouel Boudjnah"
  env: production
  defaultTheme: auto
  # disableThemeToggle: true
  # ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowToc: true
  disableSpecial1stPost: true
  ShowReadingTime: true
  homeInfoParams:
    Title: "Hi, I'm Chmouel! 👋"
    Content: "I'm a Software Engineer at Red Hat. I write about Kubernetes, Tekton, Emacs, Python, Go, and other tech adventures."
  # label:
  #   icon: logo/chmouel.png
  #   iconHeight: 40
  assets:
    disableFingerprinting: false

  editPost:
    URL: "https://github.com/chmouel/blog/tree/main/content"
    Text: "Edit"
    appendFilePath: true

markup:
  highlight:
    style: dracula
    lineNumbersInTable: false
    tabWidth: 2
    guessSyntax: true

menus:
  main:
    - name: "camera"
      url: "https://photos.chmouel.com"
      pre: Photos
      weight: 10
    - name: "GitHub"
      url: "https://github.com/chmouel/"
      weight: 20
    - name: "Mastodon"
      url: "https://fosstodon.org/@chmouel"
      weight: 30
    - name: "Twitter"
      url: "https://twitter.com/chmouel"
      weight: 40
    - name: "Strava"
      url: "https://app.strava.com/athletes/126695"
      weight: 50
    - name: "redhat"
      url: "https://redhat.com"
      pre: Red Hat
      weight: 60
    - name: "archive"
      url: "archives/"
      weight: 70
    - name: "search"
      url: "search/"
      weight: 80
privacy:
  youtube:
    privacyEnhanced: true
